[build]
  bin = "./tmp/main"
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ."
  delay = 1000
  env_file = ".env"

[watch]
  extensions = ["go", "mod", "sum"]
  exclude_dirs = ["tmp", "vendor", ".git"]

[misc]
  clean_on_exit = true